# Generated by Django 2.1.7 on 2019-05-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ercesscorp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
