# Generated by Django 2.1.7 on 2019-05-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ercesscorp', '0002_auto_20190511_0950'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
